# Generated by Django 5.2.1 on 2025-06-10 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0012_majorsubject_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_score', models.FloatField(default=0.0, help_text='歷史最高得分率 (例如 95.0)', verbose_name='最高得分率')),
                ('last_practice_session_score', models.FloatField(blank=True, help_text='最近一次完整練習會話的得分率', null=True, verbose_name='最近一次練習得分')),
                ('total_questions_answered', models.PositiveIntegerField(default=0, verbose_name='總答題數')),
                ('total_correct_answers', models.PositiveIntegerField(default=0, verbose_name='總答對題數')),
                ('last_completed_date', models.DateField(blank=True, help_text='用於計算連續學習天數', null=True, verbose_name='上次完成練習日期')),
                ('consecutive_days', models.PositiveIntegerField(default=0, help_text='連續完成練習的天數', verbose_name='連續學習天數')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_summary', to='questions.subject', verbose_name='科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_summary', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者學習進度',
                'verbose_name_plural': '使用者學習進度',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否答對')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='questions.question', verbose_name='問題')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='progress.userprogress', verbose_name='對應進度')),
            ],
            options={
                'verbose_name': '使用者作答記錄',
                'verbose_name_plural': '使用者作答記錄',
                'ordering': ['-answered_at'],
            },
        ),
    ]
