# Generated by Django 5.2.1 on 2025-05-29 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='科目名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='價格')),
                ('trial_questions_count', models.PositiveIntegerField(default=0, verbose_name='試玩題目數')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='標籤名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='題目內容')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='選項')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='正確答案')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解析')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='圖片')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='是否 AI 生成')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], db_index=True, default='medium', max_length=10, verbose_name='難度')),
                ('question_type', models.CharField(choices=[('single_choice', '單選題'), ('multiple_choice', '多選題'), ('fill_in_blank', '填空題')], db_index=True, default='single_choice', max_length=20, verbose_name='題型')),
                ('question_hash', models.CharField(db_index=True, help_text='用於題目去重，基於題目內容、選項等生成', max_length=64, unique=True, verbose_name='題目哈希值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.subject', verbose_name='所屬科目')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, related_name='questions', to='questions.tag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'difficulty'], name='questions_q_subject_384fc8_idx'), models.Index(fields=['question_type'], name='questions_q_questio_14b61e_idx')],
            },
        ),
    ]
