# Generated by Django 5.2.1 on 2025-06-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='主科目名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '主科目',
                'verbose_name_plural': '主科目',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['major_subject', 'name'], 'verbose_name': '子科目', 'verbose_name_plural': '子科目'},
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.subject', verbose_name='所屬子科目'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='子科目名稱'),
        ),
        migrations.AddField(
            model_name='subject',
            name='major_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='questions.majorsubject', verbose_name='所屬主科目'),
        ),
    ]
