# Generated by Django 5.2.1 on 2025-06-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_majorsubject_alter_subject_options_and_more'),
    ]

    operations = [
    ]
