# Generated by Django 5.2.1 on 2025-06-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_assign_default_major_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='trial_questions_count',
        ),
        migrations.AddField(
            model_name='question',
            name='is_trial',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否為試玩題目'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='major_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='questions.majorsubject', verbose_name='所屬主科目'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_trial'], name='questions_q_is_tria_0bbcad_idx'),
        ),
    ]
