# Generated by Django 5.2.1 on 2025-06-09 20:00

from django.db import migrations
from django.utils.translation import gettext_lazy as _

def assign_default_major_subject(apps, schema_editor):
    """
    Assign a default MajorSubject to any Subject that doesn't have one.
    """
    MajorSubject = apps.get_model('questions', 'MajorSubject')
    Subject = apps.get_model('questions', 'Subject')
    
    # Get or create the default "Uncategorized" MajorSubject
    default_major, created = MajorSubject.objects.get_or_create(
        name=_("未分類科目"),
        defaults={'description': _("系統自動分類的科目")}
    )
    
    # Find all subjects with no major subject and update them
    subjects_to_update = Subject.objects.filter(major_subject__isnull=True)
    if subjects_to_update.exists():
        count = subjects_to_update.update(major_subject=default_major)
        print(f'\\nUpdated {count} subjects to have a default major subject.')


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_subject_trial_questions_count_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_default_major_subject, migrations.RunPython.noop),
    ] 