# Generated by Django 5.2.1 on 2025-06-09 11:25

import django.db.models.deletion
import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_assign_default_major_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': '子科目', 'verbose_name_plural': '子科目'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='major_subject',
            field=models.ForeignKey(default=questions.models.get_default_major_subject_pk, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='questions.majorsubject', verbose_name='所屬主科目'),
        ),
    ]
