# Generated by Django 5.2.1 on 2025-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_final_options_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已發佈'),
        ),
    ]
