# Generated by Django 5.2.1 on 2025-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_subject_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorsubject',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否啟用'),
        ),
    ]
