# Generated by Django 5.2.1 on 2025-06-11 13:30

from django.db import migrations

def publish_all_subjects(apps, schema_editor):
    """
    Sets the is_published flag to True for all existing Subject objects.
    This is to ensure that subjects created before the is_published field
    was added are visible by default.
    """
    Subject = apps.get_model('questions', 'Subject')
    updated_count = Subject.objects.all().update(is_published=True)
    print(f"\\nUpdated {updated_count} subjects to be published.")

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_majorsubject_is_active'),
    ]

    operations = [
        migrations.RunPython(publish_all_subjects, migrations.RunPython.noop),
    ] 