# Generated by Django 5.2.1 on 2025-06-07 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_list', models.JSONField(help_text='本次考試抽取的 Question ID 列表, e.g., [1, 5, 10, 23]', verbose_name='問題列表')),
                ('user_answers', models.JSONField(blank=True, default=dict, help_text="儲存使用者答案的 JSON, e.g., {'1': 'A', '5': 'C'}", verbose_name='使用者答案')),
                ('score', models.FloatField(default=0.0, help_text='本次考試的最終得分率, e.g., 85.5', verbose_name='得分')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='是否完成')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='questions.subject', verbose_name='科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '模擬考試會話',
                'verbose_name_plural': '模擬考試會話',
                'ordering': ['-start_time'],
            },
        ),
    ]
